<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>SentinelAI.App</RootNamespace>
    <AssemblyName>SentinelAI</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <SatelliteResourceLanguages>fr;en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SentinelAI.Core\SentinelAI.Core.csproj" />
  </ItemGroup>

</Project>
